version: "3.9"
services:
  web:
    profiles: ['prod']
    restart: always
    environment:
      - DASH_DEBUG_MODE=False
      - HOST=0.0.0.0
    build: .
    # ports:
    #   - "8050:8050"
    container_name: adarelorg
    networks:
      - reverse_proxy_nw
    volumes:
      - .:/app

  web-dev:
    profiles: ['dev']
    environment:
      - DASH_DEBUG_MODE=True
      - FLASK_ENV=development
    build: .
    ports:
      - "8050:8050"
    volumes:
      - .:/app

networks:
  reverse_proxy_nw:
    name: reverse_proxy_nw
    external: true